### PR TITLE
fixed pending invites from favorite

### LINKED ISSUE #173: Pending invite not shown
**Describe the bug**
On the grid list view when a user was previously a member of an instance and they had favorited the instance if they are then removed and re-invited to an instance the pending invite card will not be shown unless the instance is un-favorited
**To Reproduce**

1. Invite user to instance
2. Accept invite
3. Click "favorite" instance stare
4. Remove user from the instance
5. Re-invite user from the instance
6. reload accounts
7. see pending invite card is missing but favorited instance (which user no longer has access to) card is shown
8. un-favorite instance by click star
9. see pending invite now shown

**Expected behavior**
Pending invite cards should be shown regardless of whether the instance had previously been favorited

**Screenshots**

**Additional context**
When a user is removed from an instance we should probably remove the favorited status of that instance from their preferences

### PR DESCRIPTION
**Pull request by d88naimi**
Fixes an invite that is missing if the user has favorited the instance before. 
fixes #173

### CODE REVIEW

File: src/apps/properties/src/views/PropertiesList/components/GridList/GridList.js [hunk 1]
```diff
@@ -37,6 +39,19 @@ export default connect(state => state)(props => {
     }
   }
 
+  // Fix for pending invites not shown if user has favorited the instance before. ticket #173
```
Comment (shrunyan) [inline src/apps/properties/src/views/PropertiesList/components/GridList/GridList.js:42]: @d88naimi lets put this into an on mount useEffect. Don't think we need it to run on every render. Please re-test and confirm though that if in a useEffect still gives us the behavior we want.

**Review by shrunyan — CHANGES_REQUESTED** [review]

**Review by shrunyan — APPROVED** [review]

**Review by shrunyan — APPROVED** [review]
